server:
  port: 10000

spring:
  application:
    name: 10000-czh-config
#  profiles:
#    active: native #使用spring.profiles.active=native就会自动搜索resources目录下的文件
  cloud:
    config:
      server:
        git:
#          search-paths: /src/main/resouces
          uri: https://github.com/chenzhehao/config-file.git #实时获取git上的配置文件
#          uri: https://github.com/isosweet/Config-File.git #使用用户密码的更多配置方式尚未成功
#          username: chenzhehao
#          password: 1357924680a


logging:
  config: classpath:log4j2.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10010/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
    instance-id: ${spring.cloud.client.ip-address}:${server.port}